### PR TITLE
PR: inheritance

### PR DESCRIPTION
**Pull request by darylteo**
Support for #38

1. Added logic to consider inheritance hierarchies
2. Reinstate all commented out superclass tests
3. Add an additional test for grandparent class
4. Support interface default methods
5. Support narrowed return types

### CODE REVIEW

**Comment by sdaschner** [comment]
First of all, thanks for your contribution! I'm currently busy traveling around Japan for a Nighthacking tour, but I'll take a look at your issues and PR as soon as I have more time.

Cheers!

**Comment by darylteo** [comment]
> Japan 

Jelly =) Enjoy!

**Comment by darylteo** [comment]
Hey @sdaschner any eta on this? I'm going to have to resort to running a custom build for my team for the time being, but would be more convenient to have this in 0.10 on maven if possible.

**Comment by sdaschner** [comment]
Thanks for contributing! :)
Btw, will merge the ASM branch into master today, so some changes will probably disappear due to ASM. The tests are indeed very helpful!

**Comment by darylteo** [comment]
Yay :)

**Pull request merged**
