### PR TITLE
Support for @response javadoc tag hint  

### PR DESCRIPTION
**Pull request by rmpestano**
refs #129

### CODE REVIEW

**Comment by sdaschner** [comment]
Unfortunately the JavaDoc enhancements broke your PR... I had to touch a lot of locations of the JavaDoc parsing. Could you please check again?

**Comment by rmpestano** [comment]
Hi @sdaschner,

I think it is now compatible with the new Javadoc enhancements.  

The only problem is that class level `@response` javadoc tag is not working, only resource level.

 Mainly because class level Javadoc is not being collected and then it is always [empty here](https://github.com/rmpestano/jaxrs-analyzer/blob/962ecd436307414941d5039288aad56d65340322/src/main/java/com/sebastian_daschner/jaxrs_analyzer/analysis/results/ResultInterpreter.java#L151)

I did not changed that because I did not feel I was doing the right thing ;) 

Would you look at why (or how to make) class level Javadoc tags not being collected?

I'm using the same example of issue #129 to test it.

**Comment by sdaschner** [comment]
Cool, thanks!
I'll have a look at it. The class level JavaDoc were not collected so far since there wasn't any use of it (no `@param` at that level). But your suggestion makes sense.

**Comment by sdaschner** [comment]
Merged. I refactored the model a bit. I think this fits the idea better.

It would be awesome if you could add a few scenarios to the systemtest repo: https://github.com/sdaschner/jaxrs-analyzer-st

**Comment by rmpestano** [comment]
Yes, I'll do that. Thank you.

**Pull request merged**
