### PR TITLE
Support @DefaultValue annotations and mark parameters as required/optional in swagger spec.

### PR DESCRIPTION
**Pull request by darylteo**
All tests passing thus far (except for 1 "test") that fails sporadically when running "All Tests". I'll spend some more time figuring out why.

Include Tests

Implementation for #55

### CODE REVIEW

**Comment by sdaschner** [comment]
Thanks for contributing!

One comment: The `defaultValues` doesn't need to be a `Map<String, String>`. It's sufficient to just store the value not the annotation type. You agree?

The rest though is perfect!

**Comment by darylteo** [comment]
Problem is with the annotation visitors. They all expect the param map to
be Map<String, String>.

I put in the type for now to leave it consistent in behavior with the other
visitors.

Open to discussion!

**Comment by darylteo** [comment]
@sdaschner  went with Map<String, Void> rather than Set.

**Comment by darylteo** [comment]
Hold off on pulling in... not working on my client build for some reason *frowns*... not sure what I'm missing yet.

**Comment by darylteo** [comment]
I've gone and rewrote a bunch of stuff *sigh*. @DefaultValue must be driven by parameter index, not by param name as it never gets it.

This has led to a horrible piece of code in SwaggerBackend to add the query parameters. The tests for it are there though, and it works while preserving the current mapKey sorting order. Will need your refactoring touches to make things look a bit cleaner I guess.

Good news is I've got it working on my build now, so please re-review

**Comment by sdaschner** [comment]
Ah, sorry, I overlooked something...

The default value information should in fact be gathered for all type of parameters. Having that said it is needed to add another class `MethodParameter` (containing the `type` and potential `defaultValue` or else `null`) in the `MethodParameters`. So that all the `Map<String, String>`'s will be `Map<String, MethodParameter>`'s. Do you know what I mean?

Sorry, for the confusion. At least this will make it simpler to access it in the `Backend`s then.

**Comment by darylteo** [comment]
Problem I faced when attempting that approach was that the annotations are visited one at a time.The DefaultValue annotation may come before or after the paired annotation, so it is difficult to know which map to put the annotation in, hence the introduction of the DefaultValues map.

If we change MethodParameters to only contain a List<MethodParameter>, or Map<Integer, MethodParameter>, then stream+filter that list into the correct maps for backend use, will this work for you? The annotation visitors will need to change away from extractParamMap, and just work based on Map<Integer, String>. 

I'm guessing overlooked part is other backends like asciidoc =) I wasn't using them

**Comment by darylteo** [comment]
@sdaschner  

Lots of clean up required probably, but was this what you had in mind? 

https://github.com/darylteo/jaxrs-analyzer/tree/55-default-value2

Seems to work for the most part. Most of the damage is in the test builders. Haven't decided if having the index in the MethodParameter construct is crucial, and it doesn't particularly add much, but could be worth keeping.

**Comment by sdaschner** [comment]
Yes, this is more towards it :-) I like the idea of identifying the types of parameters in one big data structure, though I would change it a litte bit.
Anyway, will merge it tomorrow and get in touch of what I was thinking of.

Thanks already for your efforts!

**Comment by darylteo** [comment]
Okay I've pushed it to 55-default-value branch. =)

**Comment by sdaschner** [comment]
Merged. Thanks a lot for your work!

Had to change a few things. The problem since the `@DefaultValue` is certainly that we must remember the parameter index or the field name, respectively -- that wasn't necessary before. However, I prefer data structures which model the final state and thus without any indexes or fields as they are only needed during analysis time and not after the method parameters have been analyzed.
That's why I moved the "identification" part of the `MethodParameter` into the *Visitors and then the `MethodParameters` seemed pretty empty, therefore I deleted that class. The *Visitors still need to be refactored -- a lot of duplicated functionality regarding the annotations, that'll be moved in abstract classes, but that's enough for today...

I liked you idea of identifying types of parameters (and having them in one place), however changed that to enums (= type safer).

Have a look and let me know your thoughts.

**Comment by darylteo** [comment]
Main struggle with being a contributor is working within the culture of the codebase without disrupting too much =) Happy for you to make the calls on these things. Definitely looks cleaner than the rush job I did 👍

**Comment by darylteo** [comment]
At risk of backtracking us on this @sdaschner , what is the justification for making queryparams mandatory by default when `@QueryParam` is always optional (as null).

Right now, having tried out @DefaultValue in various places, it's now causing me problems with Collections -> given a default value of EMPTY_STRING these collections will have 1 empty element in it always. Semantically speaking, this causes problems as there is no way to differentiate between "1 empty value" and "no value". 

Will try to figure out an workaround... :(

**Comment by sdaschner** [comment]
Actually, you're right...

So in fact the (Swagger) output for mandatory should always be `false` -- the value in the JAX-RS method is `null` then, obviously.

**Comment by darylteo** [comment]
If you really want to pull the trigger on this, we'll have to review all the different param types. 

And instead of using `@DefaultValue`, we'll have to use `@NotNull` to mark mandatory arguments as per [here](https://jersey.java.net/documentation/latest/bean-validation.html).

For the moment, my workaround is just filtering out empty values in my list, so it still works at least.

**Comment by darylteo** [comment]
ping @sdaschner let me know if you want to go ahead with this change and I'll look on the weekend likely.

**Comment by sdaschner** [comment]
Sorry for the late response. Yep, that would be the correct way.

Actually we wouldn't necessarily need the Bean Validation support at first, so only `optional: false` values in Swagger at first, but then it would be correct at least. I'm fine with having different behavior compared to previous versions, at least it's correct then. We're not at version `1.x` yet :-)

So first I would change the behavior of query parameters -- these should be always optional, at least from a technical perspective.

**Pull request merged**
