### PR TITLE
JSR 339 3.2 and Enums

### PR DESCRIPTION
**Pull request by darylteo**
Support for #59 and #50 

There is a failing test ProjectAnalyzerTest that has arisen but I'm not sure why it's suddenly appearing.
Appears related to the mocked JobRegistry in SubResourceLocatorMethodContentAnalyzerTest not getting cleaned up properly.

### CODE REVIEW

**Comment by darylteo** [comment]
ping @sdaschner

**Comment by sdaschner** [comment]
Sorry for being unresponsive, I'm having a look and'll merge it this weekend the latest. Thanks once again for your efforts!

**Comment by sdaschner** [comment]
Update: So I've already merged the PR in my working copy, but I have to adapt a few things. I found out after thinking about it that we want to decouple the logic of the enum values from the backend to the analysis time. So I'm currently changing the `MethodParameter` to include more information about the type (not only the String type) -- which can then be used in all backends. But this changes a lot more internally (tests etc.). I'm planning to push that in the next days.

However, stay tuned :-)

**Comment by darylteo** [comment]
No problems =) i'll just keep poking until results arrive :P

**Comment by sdaschner** [comment]
Finally ;-)

**Pull request merged**
